import type { NextPage } from 'next';
import Head from 'next/head';
import { ReactElement, FC } from 'react';
import Layout from '../components/Layout';

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div>메인화면</div> */}
      {/* <Test /> */}
    </>
  );
};

export default Home;

Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};
